### ISSUE TITLE
How to get required data from API calls?

### ISSUE THREAD

**Issue by suhailvs** [suhailvs/upwork_temp#2]
@RTRAaron

To get all Candidate:
run `http://api.jobadder.com/v2/candidates -H "Authorization: Bearer xxxxx` where xxxxxx is the access token, I get:
```
{
  "items": [
    {
      "candidateId": 7939153,
      "firstName": "Aaron",
      "lastName": "Dye",
      "email": "AMDYE123@GMAIL.COM",
      "status": {
        "statusId": 28882,
        "name": "Active",
        "active": true,
        "default": true
      },
      "createdBy": {
        "userId": 219893,
        "firstName": "Mint",
        "lastName": "Talent",
        "email": "support@minttalent.com",
        "mobile": " +61 451 519 135"
      },
      "createdAt": "2017-09-26T02:58:48Z",
      "updatedBy": {
        "userId": 219893,
        "firstName": "Mint",
        "lastName": "Talent",
        "email": "support@minttalent.com",
        "mobile": " +61 451 519 135"
      },
      "updatedAt": "2017-09-26T02:58:48Z",
      "links": {
        "self": "https://au2api.jobadder.com/v2/candidates/7939153"
      }
    },
    {
.....
    }
  ],
  "totalCount": 7,
  "links": {
    "first": "https://au2api.jobadder.com/v2/candidates",
    "last": "https://au2api.jobadder.com/v2/candidates"
  }
```

when i run the api call: `htts://au2api.jobadder.com/v2/candidates/7939153 -H "Authorization: Bearer xxxx`
The link can be created using candidateID
the result is:
```
{
  "candidateId": 7939153,
  "firstName": "Aaron",
  "lastName": "Dye",
  "email": "AMDYE123@GMAIL.COM",
  "status": {
    "statusId": 28882,
    "name": "Active",
    "active": true,
    "default": true
  },
  "social": {},
  "education": [],
  "custom": [],
  "recruiters": [
    {
      "userId": 219893,
      "firstName": "Mint",
      "lastName": "Talent",
      "email": "support@minttalent.com",
      "mobile": " +61 451 519 135",
      "links": {
        "self": "https://au2api.jobadder.com/v2/users/219893",
        "userGroups": "https://au2api.jobadder.com/v2/users/219893/usergroups"
      }
    }
  ],
  "createdBy": {
.....
```

From this we can get recruiters --> `firstName`,`lastName` also get statusid-->`name` -> `Active`,`Placed(PERM)` etc.

## Send Email

Now send email to `AMDYE123@GMAIL.COM` with Dynamic fields candidates -> `firstName`,`lastname` and from the second api call we get `Recruiters.firstname`.

## Questions

+ **Where is `employment.Current`?**
+ **Where is Consultants?**
+ **What is the purpose of Image Upload?**

**Comment by suhailvs** [comment]
On first API call there are 7 candidates ie:
```
      "candidateId": 7939153,
      "firstName": "Aaron",
      "lastName": "Dye",
      "email": "AMDYE123@GMAIL.COM",
...  
     "candidateId": 7937671,
      "firstName": "Chloe",
      "lastName": "Jones",
      "email": "cj@test.com",
...
      "candidateId": 7224613,
      "firstName": "Fred",
      "lastName": "Smith",
      "email": "Fredsmith@test.com",
...
    ETC
```
So the django site will create these 7 emails, and mail them with firstName and lastName.

**Comment by RTRAaron** [comment]
To get a Candidates current employer (employment.Current)
I can see it in https://api.jobadder.com/v2/docs#operation/GetCandidate 

https://i.imgur.com/TsNnSDf.png I have denoted it as employment.current because I imagine it will look something like that. (I am not a developer so the exact code is very likely to be different.)

Where is Consultants? Good question. It looks like they are from https://api.jobadder.com/v2/docs#operation/FindUsers https://i.imgur.com/c8qSHYU.png
I will add a second user today just so we have more than one in the sandbox. 


The purpose of the picture is to update the Responsive email template to contain that picture. Means that we can send it on behalf of different consultants with their picture in the template.

**Comment by suhailvs** [comment]
The endpoint `/users` (`https://api.jobadder.com/v2/users -H "Authorization: Bearer xxx"`) which returns:
```
{
  "items": [
    {
      "userId": 219893,
      "firstName": "Mint",
      "lastName": "Talent",
      "email": "support@minttalent.com",
      "mobile": " +61 451 519 135",
      "links": {
        "self": "https://au2api.jobadder.com/v2/users/219893",
        "userGroups": "https://au2api.jobadder.com/v2/users/219893/usergroups"
      }
    },
    {
      "userId": 220612,
      "firstName": "Test",
      "lastName": "User",
      "jobTitle": "Consultant",
      "email": "tempgcacc@gmail.com",
      "links": {
        "self": "https://au2api.jobadder.com/v2/users/220612",
        "userGroups": "https://au2api.jobadder.com/v2/users/220612/usergroups"
      }
    }
  ],
  "totalCount": 2,
  "links": {
    "first": "https://au2api.jobadder.com/v2/users",
    "last": "https://au2api.jobadder.com/v2/users"
  }
```
So we will provide an upload feature for these two users ie `support@minttalent.com` and `tempgcacc@gmail.com`. What about Candidates?. How will we send resposive template email with image to candidates if they are not uploaded anything?

**Comment by RTRAaron** [comment]
OK we don't need them to upload anything because the email being sent to the candidates is on behalf of the business talking about the user. 

So if a Candidate becomes placed and gets the status Placed (PERM) or Placed (Contract) then we will send a responsive email to them from info@minttalent.com with a picture of the "user" who placed them in their new job. This is why we need the user to have uploaded their picture.

**Comment by RTRAaron** [comment]
More information about the above. https://api.jobadder.com/v2/docs#operation/GetCandidate
On that page, on the right I see "status"
https://i.imgur.com/ZUahZkt.png

When a candidate is marked as placed in the system they will either get a Status of 'Placed (PERM)' or 'Placed (CONTRACT)'

E.G. https://i.imgur.com/pSCL4NR.png

See the status field in the candidate record on the CRM
this is our trigger to send them that email
