### ISSUE TITLE
Perhaps we should go down the email address and password route. 

### ISSUE THREAD

**Issue by RTRAaron** [suhailvs/upwork_temp#6]
Perhaps we should go down the email address and password route. I am concerned that anyone could access this URL and see all the companies placements.

**Comment by RTRAaron** [comment]
needs a set password workflow and a forgotten password workflow

**Comment by suhailvs** [comment]
So each `user` has `unique user name` and password?

**Comment by RTRAaron** [comment]
Yes

**Comment by suhailvs** [comment]
What about sending the password to email (which has instructions to pic upload)?

**Comment by RTRAaron** [comment]
Nah we should allow them to set their own password

**Comment by suhailvs** [comment]
@RTRAaron  By sending them a verification email?
